import Image from "next/image";
import logo from "/public/hilt-security-logo.svg";
export const metadata = {
  title: "Hilt International Security",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between py-24 bg-gradient-to-tr from-gray-200 via-slate-100 to-orange-50 animate-background bg-[length:400%_400%]">
      <div
        className="relative flex place-items-center 
        "
      >
        <Image className="w-56" src={logo} alt="Next.js Logo" priority />
      </div>
      <p className="font-semibold font-sans text-[9.4vw] md:text-7xl leading-[1] text-[#333333]">
        Coming Soon
      </p>
      <p className="text-xs text-[#333333]">© 2023</p>
    </main>
  );
}
